#remote_theme: pages-themes/minimal@v0.2.0
title: ITPCP Plasma
description: Hello! We are the Plasma Physics Group at [TU Graz](https://www.tugraz.at/fakultaeten/mpug/home/)
theme: jekyll-theme-minimal
