logo: /assets/logo-itp.png
title: ITPCP Plasma
description: Plasma Physics Group at Institute of Theoretical and Computational Physics, Graz University of Technology
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _redirects
  - extra.css
