logo: /assets/logo-itp.png
title: ITPCP Plasma
description: Hello! We are the Plasma Physics Group at Universiy of Technology Graz
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 

include: 
  - _redirects
  - extra.css
