#remote_theme: pages-themes/minimal@v0.2.0
title: ITPCP Plasma
logo: /assets/logo-itp.png
description: Hello! We are the Plasma Physics Group at Universiy of Technology Graz
theme: jekyll-theme-minimal
